# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.
[[main]]
    name = "Home"
    url = "/"
    weight = 1
[[main]]
    name = "Packages"
    url = "/packages/"
    weight = 2
[[main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
[[main]]
    name = "Projects"
    url = "/start/"
    weight = 4
[[main]]
    name = "Tutorials"
    url = "/learn/"
    weight = 5

