# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.
[[main]]
    name = "Home"
    url = "/"
    weight = 1
[[main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[main]]
    name = "Projects"
    url = "/start/"
    weight = 3

