baseurl = "https://asimumba.rbind.io/"
DefaultContentLanguage = "en"
title = "Aaron Simumba"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentsCodeFences = false
disqusShortname = "asimumba"
googleAnalytics = "UA-101235795-1"
enableEmoji = true
relativeURLs = false
socialShare = true
useHLJS = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
  post = "/:year/:month/:day/:slug/"

[Params]
  homeTitle = "Data Musings"
  subtitle = "Aspiring Data Scientist & Blogger | R & Stock Markets Enthusiast \ | Data Visualisation, R programming, Python, Tableau, and Microsoft Power BI."
  favicon = "img/favicon.ico"
  dateFormat = "2006/01/02"
  commit = false
  rss = true
  comments = true
  readingTime = false
  UseChroma = false
  GithubEdit = "https://github.com/rbind/asimumba/edit/master/content/"

#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex", "python"]
  highlightjsTheme = "github"

[[Params.bigimg]]
  src = "img/adult-art-backlit.jpg"
  desc = ""

[Author]
  website = "https://asimumba.rbind.io/"
  email = "simumbaa21@gmail.com"
  linkedin = "aaronsimumba"
  github = "asimumba"
  stackoverflow = "users/8137815/aaron-simumba"
  twitter = "asimumba21"
  facebook = "aaron.s.simumba"
  youtube = "user/aaronsimumba"

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "projects/projects"
    weight = 2

[[menu.main]]
    name = "Adventure"
    url = "travel"
    weight = 3

[[menu.main]]
    name = "CV"
    url = "https://asimumba.github.io/online-cv/"
    weight = 4
[[menu.main]]
    name = "About"
    url = "about/about/"
    weight = 5
